// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbPTyzC9a9gGNdxerbUAlmcMcRoJuiGg',
    appId: '1:811806274762:web:b5ae84380e197636a23033',
    messagingSenderId: '811806274762',
    projectId: 'ibn-bazz-masjed',
    authDomain: 'ibn-bazz-masjed.firebaseapp.com',
    storageBucket: 'ibn-bazz-masjed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7R8gq1iBXX4dH5VWoO2GFfE5W-7nTcuQ',
    appId: '1:811806274762:android:84e7d0a5ace5fa8da23033',
    messagingSenderId: '811806274762',
    projectId: 'ibn-bazz-masjed',
    storageBucket: 'ibn-bazz-masjed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6whyVeAD0FS9VjZM2lkOWBsdZIeSGvcs',
    appId: '1:811806274762:ios:0fb07abf0077de27a23033',
    messagingSenderId: '811806274762',
    projectId: 'ibn-bazz-masjed',
    storageBucket: 'ibn-bazz-masjed.firebasestorage.app',
    iosBundleId: 'com.alsalhani.ebnbazz',
  );

}